apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: log-handler 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-handler 
subjects:
- kind: ServiceAccount
  name: log-handler 
  namespace: test 
